steps:
  # Build the frontend
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'mail-merge-frontend'
      - '--source'
      - '.'
      - '--region'
      - 'us-west1'
      - '--allow-unauthenticated'
      - '--platform'
      - 'managed'

options:
  logging: CLOUD_LOGGING_ONLY
